kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    tags: "${DRONE_COMMIT_SHA}"
    repo: sathyabhat/subreddit_fetcher
  when:
      branch:
      - dev
      event:
      - push
