kind: pipeline
name: default

steps:
- name: Build
  image: plugins/docker
  network_mode: host
  settings:
    tags: ${DRONE_COMMIT_SHA}
    repo: sathyabhat/subreddit_fetcher
    username:
      from_secret: repo_username
    password:
      from_secret: repo_password

- name: Analyze
  image: anchore/engine-cli
  environment:
    ANCHORE_CLI_USER: admin
    ANCHORE_CLI_PASS:
      from_secret: anchore_password
    ANCHORE_CLI_URL: http://drone.sathyabh.at:8228/v1/
  commands:
   - anchore-cli image add sathyabhat/subreddit_fetcher:${DRONE_COMMIT_SHA}
   - anchore-cli image wait sathyabhat/subreddit_fetcher:${DRONE_COMMIT_SHA}

- name: Policy Check and Evaluation
  image: anchore/engine-cli
  environment:
    ANCHORE_CLI_USER: admin
    ANCHORE_CLI_PASS:
      from_secret: anchore_password
    ANCHORE_CLI_URL: http://drone.sathyabh.at:8228/v1/
  commands:
   - anchore-cli evaluate check sathyabhat/subreddit_fetcher:${DRONE_COMMIT_SHA} --detail
