kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    tags: 7
    repo: sathyabhat/subreddit_fetcher
    username:
      from_secret: repo_username
    password:
      from_secret: repo_password 
    debug: true
