kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    tags: "${DRONE_COMMIT_SHA}"
    repo: sathyabhat/subreddit_fetcher
    username:
      from_secret: repo_username
    password:
      from_secret: repo_password 
    debug: true

- name: scan
  image: anchore/engine-cli
  environment:
    ANCHORE_CLI_USER: admin
    ANCHORE_CLI_PASS: 
      from_secret: anchore_password
    ANCHORE_CLI_URL: http://anchore_anchore-engine_1:8228/v1/
  commands:
   - anchore-cli image add sathyabhat/subreddit_fetcher:${DRONE_COMMIT_SHA}
